apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-template-go
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  # TODO(negz): Replace me with function-dummy.
  - step: produce-composed-resources
    functionRef:
      name: some-composition-function
  - step: filter-composed-resources
    functionRef:
      name: function-cel-filter
    input:
      apiVersion: cel.fn.crossplane.io/v1beta1
      kind: Filters
      filters:
      # Remove the desired composed resource named a-desired-composed-resource
      # from the function pipeline if the XR has spec.widgets == 42.
      - name: a-desired-composed-resource
        expression: observed.composed.resource.spec.widgets == 42
